# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adadek/workspace/SoC_Design/vivado/soc_project.srcs/sources_1/bd/soc_project/ip/soc_project_ZedboardOLED_0_0/soc_project_ZedboardOLED_0_0.xci
# IP: The module: 'soc_project_ZedboardOLED_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/adadek/workspace/SoC_Design/vivado/soc_project.srcs/sources_1/bd/soc_project/ip/soc_project_ZedboardOLED_0_0/src/charLib/charLib.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# XDC: /home/adadek/workspace/SoC_Design/vivado/soc_project.srcs/sources_1/bd/soc_project/ip/soc_project_ZedboardOLED_0_0/src/charLib/charLib_ooc.xdc

# IP: /home/adadek/workspace/SoC_Design/vivado/soc_project.srcs/sources_1/bd/soc_project/ip/soc_project_ZedboardOLED_0_0/soc_project_ZedboardOLED_0_0.xci
# IP: The module: 'soc_project_ZedboardOLED_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/adadek/workspace/SoC_Design/vivado/soc_project.srcs/sources_1/bd/soc_project/ip/soc_project_ZedboardOLED_0_0/src/charLib/charLib.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# XDC: /home/adadek/workspace/SoC_Design/vivado/soc_project.srcs/sources_1/bd/soc_project/ip/soc_project_ZedboardOLED_0_0/src/charLib/charLib_ooc.xdc
