# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/adadek/SoC_Design/IPs/zedboard_audio/constraints/zed_audio.xdc

# Block Designs: bd/soc_project/soc_project.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project || ORIG_REF_NAME==soc_project} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_processing_system7_0_0/soc_project_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_processing_system7_0_0 || ORIG_REF_NAME==soc_project_processing_system7_0_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_zed_audio_0_0/soc_project_zed_audio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_zed_audio_0_0 || ORIG_REF_NAME==soc_project_zed_audio_0_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_xlconstant_0_1/soc_project_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_xlconstant_0_1 || ORIG_REF_NAME==soc_project_xlconstant_0_1} -quiet] -quiet

# XDC: bd/soc_project/soc_project_ooc.xdc
