# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/adadek/workspace/SoC_Design/IPs/zedboard_audio/constraints/zed_audio.xdc

# XDC: /home/adadek/workspace/SoC_Design/IPs/OLED/oled_constraints.xdc

# Block Designs: bd/soc_project/soc_project.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project || ORIG_REF_NAME==soc_project} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_processing_system7_0_0/soc_project_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_processing_system7_0_0 || ORIG_REF_NAME==soc_project_processing_system7_0_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_zed_audio_0_0/soc_project_zed_audio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_zed_audio_0_0 || ORIG_REF_NAME==soc_project_zed_audio_0_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_xlconstant_0_1/soc_project_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_xlconstant_0_1 || ORIG_REF_NAME==soc_project_xlconstant_0_1} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_FILTER_IIR_0_0/soc_project_FILTER_IIR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_FILTER_IIR_0_0 || ORIG_REF_NAME==soc_project_FILTER_IIR_0_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_ps7_0_axi_periph_0/soc_project_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_ps7_0_axi_periph_0 || ORIG_REF_NAME==soc_project_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_rst_ps7_0_100M_0/soc_project_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_rst_ps7_0_100M_0 || ORIG_REF_NAME==soc_project_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_Volume_Pregain_0_0/soc_project_Volume_Pregain_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_Volume_Pregain_0_0 || ORIG_REF_NAME==soc_project_Volume_Pregain_0_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_xbar_0/soc_project_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_xbar_0 || ORIG_REF_NAME==soc_project_xbar_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_AXI_AUDIO_0_0/soc_project_AXI_AUDIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_AXI_AUDIO_0_0 || ORIG_REF_NAME==soc_project_AXI_AUDIO_0_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_Volume_Pregain_1_0/soc_project_Volume_Pregain_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_Volume_Pregain_1_0 || ORIG_REF_NAME==soc_project_Volume_Pregain_1_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_FILTER_IIR_1_0/soc_project_FILTER_IIR_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_FILTER_IIR_1_0 || ORIG_REF_NAME==soc_project_FILTER_IIR_1_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_mixer_0_0/soc_project_mixer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_mixer_0_0 || ORIG_REF_NAME==soc_project_mixer_0_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_xlconcat_0_0/soc_project_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_xlconcat_0_0 || ORIG_REF_NAME==soc_project_xlconcat_0_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_ZedboardOLED_0_0/soc_project_ZedboardOLED_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_ZedboardOLED_0_0 || ORIG_REF_NAME==soc_project_ZedboardOLED_0_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_axi_gpio_0_0/soc_project_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_axi_gpio_0_0 || ORIG_REF_NAME==soc_project_axi_gpio_0_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_axi_gpio_1_0/soc_project_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_axi_gpio_1_0 || ORIG_REF_NAME==soc_project_axi_gpio_1_0} -quiet] -quiet

# IP: bd/soc_project/ip/soc_project_auto_pc_0/soc_project_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_project_auto_pc_0 || ORIG_REF_NAME==soc_project_auto_pc_0} -quiet] -quiet

# XDC: bd/soc_project/soc_project_ooc.xdc
